import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#1e293b",
        "secondary-container": "#f1f5f9",
        "on-tertiary-fixed": "#042f2e",
        tertiary: "#0d9488",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#0f766e",
        "primary-container": "#dbeafe",
        outline: "#e2e8f0",
        "primary-fixed": "#dbeafe",
        "surface-bright": "#ffffff",
        "surface-container": "#f1f3fc",
        "surface-variant": "#f1f5f9",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#1e3a8a",
        "error-container": "#fee2e2",
        "tertiary-container": "#ccfbf1",
        "surface-dim": "#f6f7f8",
        "primary-fixed-dim": "#bfdbfe",
        "on-error-container": "#7f1d1d",
        "on-surface-variant": "#64748b",
        surface: "#ffffff",
        "surface-tint": "#197fe6",
        "on-secondary-fixed-variant": "#334155",
        "on-secondary-fixed": "#0f172a",
        "surface-container-highest": "#e0e2eb",
        "outline-variant": "#cbd5e1",
        error: "#ef4444",
        "on-surface": "#0f172a",
        "tertiary-fixed": "#ccfbf1",
        primary: "#197fe6",
        "inverse-on-surface": "#f1f5f9",
        secondary: "#475569",
        "on-error": "#ffffff",
        "on-primary-container": "#1e40af",
        "on-secondary-container": "#1e293b",
        "inverse-primary": "#93c5fd",
        "surface-container-high": "#ebedf7",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#1d4ed8",
        "on-background": "#0f172a",
        "on-tertiary-container": "#134e4a",
        "secondary-fixed": "#e2e8f0",
        "surface-container-low": "#f6f7f8",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#cbd5e1",
        "tertiary-fixed-dim": "#99f6e4",
        background: "#f6f7f8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};

export default config;
